SELECT hao.organization_id as bu_id,
       haot.name
FROM
       HR_ALL_ORGANIZATION_UNITS_F hao,
       HR_ORGANIZATION_UNITS_F_TL haot
WHERE
       hao.ORGANIZATION_ID = haot.ORGANIZATION_ID
   AND hao.EFFECTIVE_START_DATE = haot.EFFECTIVE_START_DATE
   AND hao.EFFECTIVE_END_DATE = haot.EFFECTIVE_END_DATE
   AND TRUNC(SYSDATE) BETWEEN hao.EFFECTIVE_START_DATE AND hao.EFFECTIVE_END_DATE
   AND haot.LANGUAGE='US'
   AND haot.name = :P_BU_NAME;
---------------------------------------------------------------------
SELECT 
     OU.ORGANIZATION_ID ID AS d,
     HO.name NAME AS v
FROM 
      HR_ALL_ORGANIZATION_UNITS_F OU,
      HR_ORGANIZATION_UNITS_F_TL HO
WHERE 1=1
AND OU.ORGANIZATION_ID = HO.ORGANIZATION_ID
AND HO.LANGUAGE = 'US'
AND TRUNC(SYSDATE) BETWEEN OU.EFFECTIVE_START_DATE AND OU.EFFECTIVE_END_DATE
