SELECT  
        ESI.ITEM_NUMBER,
        QPLB.CURRENCY_CODE "Price List Currency",
        QPLC.BASE_PRICE "Price List ITem Price"               
FROM    
        EGP_SYSTEM_ITEMS ESI,
        QP_PRICE_LISTS_ALL_B QPLB,
        QP_PRICE_LISTS_TL QPLT,
        QP_PRICE_LIST_ITEMS QPLI,
        QP_PRICE_LIST_CHARGES QPLC
WHERE 1=1
AND ESI.ORGANIZATION_ID=300000118783270
AND ESI.INVENTORY_ITEM_ID = 100000209829072
AND ESI.ITEM_NUMBER = 'CM4751400'
AND QPLI.ITEM_ID=ESI.INVENTORY_ITEM_ID
AND QPLT.PRICE_LIST_ID = QPLI.PRICE_LIST_ID
AND QPLB.CURRENCY_CODE = 'USD'
AND QPLB.PRICE_LIST_ID=QPLI.PRICE_LIST_ID
AND QPLC.PARENT_ENTITY_ID (+) = QPLI.PRICE_LIST_ITEM_ID
ORDER BY 1

