--100000209829072


   --ITEM CATEGORY ID 100000000457158
   --300000118783270 dallas

--SELECT * FROM EGP_SYSTEM_ITEMS_B WHERE ORGANIZATION_ID = 300000118783270 AND ITEM_NUMBER = 'CM4751400'--PRINCIPAL SEGUN YO
--SELECT * FROM EGP_ITEM_CATEGORIES WHERE INVENTORY_ITEM_ID = 100000209829072 AND ORGANIZATION_ID = 300000118783270--SACAR CATEGORIA
--SELECT CATEGORY_NAME FROM EGP_CATEGORIES_TL WHERE CATEGORY_ID = 300000047292698 AND LANGUAGE = 'US' --NOMBRE DE LA CATEGORIA
--SELECT DESCRIPTION FROM EGP_SYSTEM_ITEMS_TL WHERE INVENTORY_ITEM_ID = 100000209829072 AND LANGUAGE = 'US' AND ORGANIZATION_ID = 300000118783270 --DESCRIPCION CREO YO

SELECT SUM(PRIMARY_QUANTITY) FROM INV_MATERIAL_TXNS WHERE ORGANIZATION_ID = 300000118783270 AND INVENTORY_ITEM_ID = 100000209829072 GROUP BY
--------------------------------------------------egp_item_org_associations
SELECT * FROM INV_LOT_NUMBERS WHERE INVENTORY_ITEM_ID = 100000209829072 --lote
SELECT SERIAL_NUMBER FROM INV_SERIAL_NUMBERS WHERE INVENTORY_ITEM_ID = 100000209829072 AND CURRENT_ORGANIZATION_ID = 300000118783270--SERIAL
SELECT * FROM INV_ONHAND_QUANTITIES_DETAIL WHERE INVENTORY_ITEM_ID = 100000209829072 AND ORGANIZATION_ID = 300000118783270

SELECT * FROM INV_ITEM_LOCATIONS WHERE ORGANIZATION_ID = 300000118783270
--inv_secondary_inventories para los subinventarios
--inv_transaction
--onhand
SELECT 
    ESI.ITEM_NUMBER ,
    ESI.DESCRIPTION ,
    IOQD.SUBINVENTORY_CODE,
    IOQD.LOT_NUMBER,
    SUM(IOQD.TRANSACTION_QUANTITY) TRX_QTY,
    UOMT.UNIT_OF_MEASURE,
    IIL.INVENTORY_LOCATION_ID,
    EGT.CATEGORY_NAME
FROM 
    INV_ONHAND_QUANTITIES_DETAIL IOQD ,
    EGP_SYSTEM_ITEMS ESI ,
    INV_ORG_PARAMETERS IOP ,
    INV_ORGANIZATION_DEFINITIONS_V IODV,
    INV_UNITS_OF_MEASURE_TL UOMT ,
    INV_UNITS_OF_MEASURE_B UOMB,
    INV_ITEM_LOCATIONS IIL,
    EGP_ITEM_CATEGORIES EIC,
    EGP_CATEGORIES_TL EGT
WHERE 1 = 1
AND IODV.ORGANIZATION_ID    = IOP.ORGANIZATION_ID
AND IOQD.INVENTORY_ITEM_ID  = ESI.INVENTORY_ITEM_ID
AND IOQD.ORGANIZATION_ID    = ESI.ORGANIZATION_ID
AND ESI.ORGANIZATION_ID     = IOP.ORGANIZATION_ID
AND UOMT.UNIT_OF_MEASURE_ID = UOMB.UNIT_OF_MEASURE_ID
AND UOMT.LANGUAGE = 'US'
AND UOMB.UOM_CODE           = IOQD.TRANSACTION_UOM_CODE
AND IOQD.ORGANIZATION_ID    = IIL.ORGANIZATION_ID(+)
AND IOQD.SUBINVENTORY_CODE  = IIL.SUBINVENTORY_CODE(+)
AND IOQD.LOCATOR_ID         =IIL.INVENTORY_LOCATION_ID(+)
and ESI.INVENTORY_ITEM_ID = EIC.INVENTORY_ITEM_ID(+)--
and ESI.organization_id = EIC.organization_id(+)--
AND EGT.CATEGORY_ID = EIC.CATEGORY_ID
AND EGT.LANGUAGE = 'US'
AND ESI.ITEM_NUMBER        = 'CM4751400'
AND ESI.ORGANIZATION_ID = 300000118783270
GROUP BY 
  ESI.ITEM_NUMBER ,
  ESI.DESCRIPTION ,
  UOMT.UNIT_OF_MEASURE ,
  IOQD.SUBINVENTORY_CODE ,
  IOQD.LOT_NUMBER,
  IIL.INVENTORY_LOCATION_ID,
  EGT.CATEGORY_NAME
ORDER BY 1,2

    SUM(IMT.PRIMARY_QUANTITY) TRX_QTY,
    INV_MATERIAL_TXNS IMT
AND IMT.INVENTORY_ITEM_ID = ESI.INVENTORY_ITEM_ID
AND IMT.ORGANIZATION_ID = ESI.ORGANIZATION_ID
AND IMT.SUBINVENTORY_CODE = IOQD.SUBINVENTORY_CODE


select	 "PO_HEADERS_ALL"."SEGMENT1" as "No_Orden_de_compra",
	 "PO_HEADERS_ALL"."CURRENCY_CODE" as "Moneda",
	 "PO_HEADERS_ALL"."APPROVED_FLAG" as "Estatus_de_aprobacion",
	 "PO_HEADERS_ALL"."APPROVED_DATE" as "Fecha_de_aprobacion",
	 "PO_LINES_ALL"."LINE_NUM" as "Numero_de_linea",
	 "PO_LINES_ALL"."UOM_CODE" as "Unidad_de_medida_uom",
	 "PO_LINE_LOCATIONS_ALL"."QUANTITY" as "Cantidad",
	 "PO_LINE_LOCATIONS_ALL"."QUANTITY_RECEIVED" as "Cantidad_recibida",
	 "PO_LINE_LOCATIONS_ALL"."QUANTITY_ACCEPTED" as "Cantidad_Aceptada",
	 "PO_LINES_ALL"."UNIT_PRICE" as "Precio_unitario",
	 "PO_LINES_ALL"."ITEM_DESCRIPTION" as "Desc_line",
	 "PO_LINES_ALL"."ITEM_ID" as "Item_ID",
	 "HZ_PARTIES"."PARTY_NAME" as "Nombre_Proovedor",
	 "POZ_SUPPLIERS"."SEGMENT1" as "Numero_de_proovedor",
	 "POZ_SUPPLIERS"."VENDOR_TYPE_LOOKUP_CODE" as "Tipo_de_Proovedor",
	 "PO_LINE_TYPES_TL"."LANGUAGE" as "Lenguaje",
	 "PO_LINE_TYPES_TL"."LINE_TYPE" as "Tip_Line",
	 "POR_REQUISITION_HEADERS_ALL"."REQUISITION_NUMBER" as "Numero_Requisicion",
	 "POR_REQUISITION_HEADERS_ALL"."DESCRIPTION" as "Desc_requi", 
	(SELECT DISTINCT esi.item_number
	  FROM egp_system_items_b esi
	  WHERE esi.inventory_item_id=PO_LINES_ALL.item_id) ITEM
	 
 from	"FUSION"."POR_REQUISITION_LINES_ALL" "POR_REQUISITION_LINES_ALL",
	"FUSION"."POR_REQUISITION_HEADERS_ALL" "POR_REQUISITION_HEADERS_ALL",
	"FUSION"."POR_REQ_DISTRIBUTIONS_ALL" "POR_REQ_DISTRIBUTIONS_ALL",
	"FUSION"."PO_DISTRIBUTIONS_ALL" "PO_DISTRIBUTIONS_ALL",
	"FUSION"."PO_LINE_TYPES_TL" "PO_LINE_TYPES_TL",
	"FUSION"."PO_LINE_LOCATIONS_ALL" "PO_LINE_LOCATIONS_ALL",
	"FUSION"."HZ_PARTIES" "HZ_PARTIES",
	"FUSION"."POZ_SUPPLIERS" "POZ_SUPPLIERS",
	"FUSION"."PO_LINES_ALL" "PO_LINES_ALL",
	"FUSION"."PO_HEADERS_ALL" "PO_HEADERS_ALL" 
 where   "PO_LINES_ALL"."PO_HEADER_ID"="PO_HEADERS_ALL"."PO_HEADER_ID"
 and	 "HZ_PARTIES"."PARTY_ID"="POZ_SUPPLIERS"."PARTY_ID"
 and	 "PO_HEADERS_ALL"."VENDOR_ID"="POZ_SUPPLIERS"."VENDOR_ID"
 and	 "PO_LINES_ALL"."PO_HEADER_ID"="PO_LINE_LOCATIONS_ALL"."PO_HEADER_ID"
 and	 "PO_LINES_ALL"."PO_LINE_ID"="PO_LINE_LOCATIONS_ALL"."PO_LINE_ID"
 and	 "PO_LINES_ALL"."LINE_TYPE_ID"="PO_LINE_TYPES_TL"."LINE_TYPE_ID"
 and	 "PO_DISTRIBUTIONS_ALL"."PO_HEADER_ID"="PO_HEADERS_ALL"."PO_HEADER_ID"
 --and	 "PO_DISTRIBUTIONS_ALL"."PO_HEADER_ID"="PO_HEADERS_ALL"."PO_HEADER_ID"
 and	 "PO_DISTRIBUTIONS_ALL"."REQ_DISTRIBUTION_ID"="POR_REQ_DISTRIBUTIONS_ALL"."DISTRIBUTION_ID"
 and	 "POR_REQ_DISTRIBUTIONS_ALL"."REQUISITION_LINE_ID"="POR_REQUISITION_LINES_ALL"."REQUISITION_LINE_ID"
 and	 "POR_REQUISITION_LINES_ALL"."REQUISITION_HEADER_ID"="POR_REQUISITION_HEADERS_ALL"."REQUISITION_HEADER_ID"
  --and 	 "PO_HEADERS_ALL"."SEGMENT1" ='267' 
   and	 "PO_LINE_TYPES_TL"."LANGUAGE" ='E'
    and POR_REQUISITION_HEADERS_ALL.REQUISITION_NUMBER = NVL(:P_REQ_NUM,POR_REQUISITION_HEADERS_ALL.REQUISITION_NUMBER)
